// react/src/routes/Home.js
import React, { Component } from "react";

import { Heading } from "../components/heading";
import Paragraph from "../components/paragraph";
import { TextLink } from "../components/links";

class Home extends Component {
  render() {
    return (
      <>
        <Heading>home</Heading>
        <Paragraph>
          Welcome. This is my home on the web. I dramatically simplified the
          site and I hope that you like it. I'm always available for public
          comment. Please send an email to{" "}
          <TextLink href="mailto:darrenjaworski@gmail.com">
            darrenjaworski@gmail.com
          </TextLink>{" "}
          . (Please allow 10-15 months for response.)
        </Paragraph>
        <Paragraph>
          Check out my past work in{" "}
          <TextLink href="/journalism">journalism</TextLink> and what I'm
          currently hacking away at in{" "}
          <TextLink href="/projects">projects</TextLink>.
        </Paragraph>
        <Paragraph>
          As always you can find me on{" "}
          <TextLink href="https://twitter.com/darrenjaws">Twitter</TextLink>,{" "}
          <TextLink href="https://www.facebook.com/DarrenJJaworski">
            Facebook
          </TextLink>
          ,{" "}
          <TextLink href="https://www.instagram.com/darrenjaws/">
            Instagram
          </TextLink>
          ,{" "}
          <TextLink href="https://www.linkedin.com/in/darrenjaworski">
            LinkedIn
          </TextLink>
          , <TextLink href="https://github.com/darrenjaworski">Github</TextLink>
          ,{" "}
          <TextLink href="http://bl.ocks.org/darrenjaworski">
            bl.ocks.org
          </TextLink>
          , 
          <TextLink href="https://medium.com/@DarrenJaws">
            Medium
          </TextLink>,{" "}
          <TextLink href="https://www.strava.com/athletes/3266824">
            Strava
          </TextLink>
          ... (I'm sure I'm missing others. You get the point. Troll away.)
        </Paragraph>
        <Paragraph>
          For those interested in watching me wear a tie and answer questions:{" "}
          <TextLink href="https://docs.google.com/document/d/19L1W3PXUyboaUWB0shDedjKwzRPsqiBw0VxsAir45EU/edit?usp=sharing">
            résumé
          </TextLink>
          .
        </Paragraph>
      </>
    );
  }
}

export default Home;

// vue/src/components/Home.vue
<template>
  <div>
    <h1>home</h1>
    <p>Welcome. This is my home on the web. I dramatically simplified the site and I hope that you like it. I'm always available for public comment. Please send an email to <a href="mailto:darrenjaworski@gmail.com">darrenjaworski@gmail.com</a> . (Please allow 10-15 months for response.)</p>
    <!-- <p>I'll be posting plenty more works of <a href="/fiction">fiction</a>. Just as soon as my fingers hit the keyboard and actually produce words and sentences that are any good.</p> -->
    <p>Check out my past work in <a href="/journalism">journalism</a> and what I'm currently hacking away at in <a href="/projects">projects</a>.</p>
    <p>As always you can find me on <a href="https://twitter.com/darrenjaws">Twitter</a>, <a href="https://www.facebook.com/DarrenJJaworski">Facebook</a>, <a href="https://www.instagram.com/darrenjaws/">Instagram</a>, <a href="https://www.linkedin.com/in/darrenjaworski">LinkedIn</a>, <a href="https://github.com/darrenjaworski">Github</a>, <a href="http://bl.ocks.org/darrenjaworski">bl.ocks.org</a>, <a href="https://medium.com/@DarrenJaws">Medium</a>, <a href="https://www.strava.com/athletes/3266824">Strava</a>... (I'm sure I'm missing others. You get the point. Troll away.)</p><p>For those interested in watching me wear a tie and answer questions: <a href="https://docs.google.com/document/d/19L1W3PXUyboaUWB0shDedjKwzRPsqiBw0VxsAir45EU/edit?usp=sharing">résumé</a>.</p>
  </div>
</template>
