// react/src/Components/Journalism.js
import React, {Component} from 'react';

class Journalism extends Component {
  render() {
    return (
      <main>
        <h1>journalism</h1>
        <h2>oklahoma watch</h2>

        <ul>
          <li>
            <a href="http://oklahomawatch.org/2013/07/22/oklahomas-correctional-facilities/">Oklahoma Correctional Facilities</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/07/24/the-mcalester-prison-riot/">Big Mac Riot of 73</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/07/22/oklahoma-state-penitentiary/">Oklahoma State Penitentiary</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/07/26/charting-inmate-counts/">Oklahoma Inmate Counts</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/07/20/oklahoma-watch-study-identifies-jobs-with-most-uninsured-workers/">OK Watch Study Identifies Uninsured Workers</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/07/17/the-uninsured/">Where the Uninsured Work</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/07/10/permits-for-handgun-licenses-keep-rising/">Handgun Permits</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/06/30/data-driven-a-measure-of-hunger/">A Measure of Hunger</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/06/24/cost-of-attendance/">Cost of Attendance</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/05/24/where-tornados-strike/">Where Tornadoes Strike (article)</a>
          </li>
          <li>
            <a href="http://darrenjaworski.cartodb.com/tables/tornadoes90_13/embed_map?title=false&amp;description=false&amp;search=false&amp;shareable=false&amp;cartodb_logo=true&amp;scrollwheel=false&amp;sql=&amp;sw_lat=33.76088200086917&amp;sw_lon=-103.86474609375&amp;ne_lat=37&amp;ne_lon=-93.31787109374999&amp;height=600&amp;id=cartodb-1369334401177">Where Tornadoes Strike (working graphic)</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/05/10/data-driven-spin-the-wheel-to-analyze-the-state-budget/">Interactive Sunburst Partition of the State Budget</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/04/02/data-center-profile-of-oklahoma-legislature/">Interactive of the State Legislature (article)</a>
          </li>
          <li>
            <a href="http://games.darrenjaworski.com/legislative-graphic/">Interactive of the State Legislature (working graphic)</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/02/19/where-the-states-stand-on-medicaid-expansion/">Where the States Stand on Medicaid Expansion</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/04/17/mapping-obesity-in-oklahoma/">Mapping Obesity in Oklahoma</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/05/08/what-oklahoma-hospitals-charge/">Comparing What Oklahoma Hospitals Charge</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/04/26/data-driven-locating-the-uninsured/">Locating the Uninsured</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/03/27/reading-test-results-for-oklahoma-schools-and-districts/">Reading Test Results for Oklahoma Schools and Districts</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/03/15/oklahoma-lake-levels-decline/">Where Lake Levels Stand</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/03/01/making-short-work-of-an-average-life/">Making Short Work of an Average Life</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/02/20/ou-and-osu-graduation-rates-comparison/">The Growing, but Still Elusive, 4-Year College Degree</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2013/01/29/firearm-deaths-in-ok-and-us/">Firearm Deaths in Oklahoma</a>
          </li>
          <li>
            <a href="http://oklahomawatch.org/2012/11/09/visualizations-of-ok-hispanic-population/">Visualizations of Oklahomas Hispanic Population</a>
          </li>
        </ul>
        <h2>routes</h2>

        <ul>
          <li>
            <a href="http://routes.ou.edu/?p=467">Captain Separated from Family for 10 years</a>
          </li>
          <li>
            <a href="http://routes.ou.edu/?p=170">Challenging Oklahoma Voter ID Law</a>
          </li>
          <li>
            <a href="http://routes.ou.edu/?p=167">Voter identification laws strengthened</a>
          </li>
        </ul>
        <h2>politically scientific</h2>

        <ul>
          <li>
            <a href="http://wandering-blog.blogspot.com/">Politically Scientific</a>
          </li>
          <li>
            <a href="http://wandering-blog.blogspot.com/2011/11/on-bacteria-and-economics.html">On Bacteria and Economics</a>
          </li>
          <li>
            <a href="http://wandering-blog.blogspot.com/2011/10/job-killing-government-regulation.html">Attack of the Job Killers!</a>
          </li>
          <li>
            <a href="http://wandering-blog.blogspot.com/2011/10/whats-going-on.html">Whats Happening Brother?</a>
          </li>
          <li>
            <a href="https://www.dropbox.com/s/t6w8x3qw8xea04a/logoKeynote.pdf?dl=0">Logo Design</a>
          </li>
          <li>
            <a href="https://www.dropbox.com/s/3emisej5tg0ltf6/authorinfographic.jpg?dl=1">Author Infographic</a>
          </li>
        </ul>
        <h2>journalism master's research</h2>

        <ul>
          <li>
            <a href="https://www.dropbox.com/s/vmj3cxm8wa1l5xm/sciencecommunication.pdf?dl=0">Online Science Communication and Public Science Literacy</a>
          </li>
          <li>Digital News Flow in an Online Oklahoma Network of Sources Authorities and Hubs</li>
        </ul>
      </main>
    )
  }
}

export default Journalism;

// vue/src/components/Journalism.vue
<template>
<div>
  <h1>journalism</h1>
  <h2>oklahoma watch</h2>

  <ul>
    <li><a href="http://oklahomawatch.org/2013/07/22/oklahomas-correctional-facilities/">Oklahoma Correctional Facilities</a></li>
    <li><a href="http://oklahomawatch.org/2013/07/24/the-mcalester-prison-riot/">Big Mac Riot of 73</a></li>
    <li><a href="http://oklahomawatch.org/2013/07/22/oklahoma-state-penitentiary/">Oklahoma State Penitentiary</a></li>
    <li><a href="http://oklahomawatch.org/2013/07/26/charting-inmate-counts/">Oklahoma Inmate Counts</a></li>
    <li><a href="http://oklahomawatch.org/2013/07/20/oklahoma-watch-study-identifies-jobs-with-most-uninsured-workers/">OK Watch Study Identifies Uninsured Workers</a></li>
    <li><a href="http://oklahomawatch.org/2013/07/17/the-uninsured/">Where the Uninsured Work</a></li>
    <li><a href="http://oklahomawatch.org/2013/07/10/permits-for-handgun-licenses-keep-rising/">Handgun Permits</a></li>
    <li><a href="http://oklahomawatch.org/2013/06/30/data-driven-a-measure-of-hunger/">A Measure of Hunger</a></li>
    <li><a href="http://oklahomawatch.org/2013/06/24/cost-of-attendance/">Cost of Attendance</a></li>
    <li><a href="http://oklahomawatch.org/2013/05/24/where-tornados-strike/">Where Tornadoes Strike (article)</a></li>
    <li><a href="http://darrenjaworski.cartodb.com/tables/tornadoes90_13/embed_map?title=false&amp;description=false&amp;search=false&amp;shareable=false&amp;cartodb_logo=true&amp;scrollwheel=false&amp;sql=&amp;sw_lat=33.76088200086917&amp;sw_lon=-103.86474609375&amp;ne_lat=37&amp;ne_lon=-93.31787109374999&amp;height=600&amp;id=cartodb-1369334401177">Where Tornadoes Strike (working graphic)</a></li>
    <li><a href="http://oklahomawatch.org/2013/05/10/data-driven-spin-the-wheel-to-analyze-the-state-budget/">Interactive Sunburst Partition of the State Budget</a></li>
    <li><a href="http://oklahomawatch.org/2013/04/02/data-center-profile-of-oklahoma-legislature/">Interactive of the State Legislature (article)</a></li>
    <li><a href="http://games.darrenjaworski.com/legislative-graphic/">Interactive of the State Legislature (working graphic)</a></li>
    <li><a href="http://oklahomawatch.org/2013/02/19/where-the-states-stand-on-medicaid-expansion/">Where the States Stand on Medicaid Expansion</a></li>
    <li><a href="http://oklahomawatch.org/2013/04/17/mapping-obesity-in-oklahoma/">Mapping Obesity in Oklahoma</a></li>
    <li><a href="http://oklahomawatch.org/2013/05/08/what-oklahoma-hospitals-charge/">Comparing What Oklahoma Hospitals Charge</a></li>
    <li><a href="http://oklahomawatch.org/2013/04/26/data-driven-locating-the-uninsured/">Locating the Uninsured</a></li>
    <li><a href="http://oklahomawatch.org/2013/03/27/reading-test-results-for-oklahoma-schools-and-districts/">Reading Test Results for Oklahoma Schools and Districts</a></li>
    <li><a href="http://oklahomawatch.org/2013/03/15/oklahoma-lake-levels-decline/">Where Lake Levels Stand</a></li>
    <li><a href="http://oklahomawatch.org/2013/03/01/making-short-work-of-an-average-life/">Making Short Work of an Average Life</a></li>
    <li><a href="http://oklahomawatch.org/2013/02/20/ou-and-osu-graduation-rates-comparison/">The Growing, but Still Elusive, 4-Year College Degree</a></li>
    <li><a href="http://oklahomawatch.org/2013/01/29/firearm-deaths-in-ok-and-us/">Firearm Deaths in Oklahoma</a></li>
    <li><a href="http://oklahomawatch.org/2012/11/09/visualizations-of-ok-hispanic-population/">Visualizations of Oklahomas Hispanic Population</a></li>
  </ul>
  <h2>routes</h2>

  <ul>
    <li><a href="http://routes.ou.edu/?p=467">Captain Separated from Family for 10 years</a></li>
    <li><a href="http://routes.ou.edu/?p=170">Challenging Oklahoma Voter ID Law</a></li>
    <li><a href="http://routes.ou.edu/?p=167">Voter identification laws strengthened</a></li>
  </ul>
  <h2>politically scientific</h2>

  <ul>
    <li><a href="http://wandering-blog.blogspot.com/">Politically Scientific</a></li>
    <li><a href="http://wandering-blog.blogspot.com/2011/11/on-bacteria-and-economics.html">On Bacteria and Economics</a></li>
    <li><a href="http://wandering-blog.blogspot.com/2011/10/job-killing-government-regulation.html">Attack of the Job Killers!</a></li>
    <li><a href="http://wandering-blog.blogspot.com/2011/10/whats-going-on.html">Whats Happening Brother?</a></li>
    <li><a href="https://www.dropbox.com/s/t6w8x3qw8xea04a/logoKeynote.pdf?dl=0">Logo Design</a></li>
    <li><a href="https://www.dropbox.com/s/3emisej5tg0ltf6/authorinfographic.jpg?dl=1">Author Infographic</a></li>
  </ul>
  <h2>journalism master's research</h2>

  <ul>
    <li><a href="https://www.dropbox.com/s/vmj3cxm8wa1l5xm/sciencecommunication.pdf?dl=0">Online Science Communication and Public Science Literacy</a></li>
    <li>Digital News Flow in an Online Oklahoma Network of Sources Authorities and Hubs</li>
  </ul>
</div>
</template>
